import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:nhasixapp/core/config/config_models.dart';
import 'package:nhasixapp/core/config/remote_config_service.dart';
import 'package:nhasixapp/core/di/service_locator.dart';
// Use correct path for AppLocalizations if generated by flutter_gen
// Usually standard is:
import 'package:nhasixapp/l10n/app_localizations.dart';
import 'package:nhasixapp/presentation/cubits/source/source_cubit.dart';
import 'package:nhasixapp/presentation/cubits/source/source_state.dart'; // Ensure correct path for state
import 'package:nhasixapp/presentation/pages/search/form_based_search_ui.dart';
import 'package:nhasixapp/presentation/pages/search/query_string_search_ui.dart';
import 'package:nhasixapp/presentation/widgets/app_scaffold_with_offline.dart';

class SearchScreen extends StatefulWidget {
  final String? query;

  const SearchScreen({
    super.key,
    this.query,
  });

  @override
  State<SearchScreen> createState() => _SearchScreenState();
}

class _SearchScreenState extends State<SearchScreen> {
  @override
  Widget build(BuildContext context) {
    return AppScaffoldWithOffline(
      title: AppLocalizations.of(context)?.searchTitle ?? 'Search',
      body: BlocBuilder<SourceCubit, SourceState>(
        builder: (context, sourceState) {
          final sourceId = sourceState.activeSource?.id ?? 'nhentai';
          final sourceConfig = getIt<RemoteConfigService>().getConfig(sourceId);
          final searchConfig = sourceConfig?.searchConfig;

          if (searchConfig == null) {
            return _buildFallbackUI(sourceId);
          }

          switch (searchConfig.searchMode) {
            case SearchMode.queryString:
              return QueryStringSearchUI(
                config: searchConfig,
                sourceId: sourceId,
                initialQuery: widget.query,
              );
            case SearchMode.formBased:
              return FormBasedSearchUI(
                config: searchConfig,
                sourceId: sourceId,
              );
          }
        },
      ),
    );
  }

  Widget _buildFallbackUI(String sourceId) {
    return Center(
      child: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            const Icon(Icons.search_off, size: 48, color: Colors.orange),
            const SizedBox(height: 16),
            Text(
              'Search configuration unavailable for $sourceId',
              style: Theme.of(context).textTheme.titleMedium,
              textAlign: TextAlign.center,
            ),
            const SizedBox(height: 8),
            const Text(
              'Please check your internet connection or try reloading the application.',
              textAlign: TextAlign.center,
            ),
          ],
        ),
      ),
    );
  }
}
