name: kuron
repository: https://github.com/nhasix/kuron

packages:
  - .
  - packages/*

sdkPath: .fvm/flutter_sdk

scripts:
  bootstrap:
    run: melos exec -- fvm flutter pub get
    description: Run pub get in all packages

  analyze:
    run: melos exec -- fvm flutter analyze --no-fatal-infos
    description: Run flutter analyze in all packages

  test:
    run: melos exec -- fvm flutter test
    description: Run tests in all packages
    packageFilters:
      dirExists: test

  format:
    run: melos exec -- fvm dart format .
    description: Format all Dart files

  codegen:
    run: fvm flutter pub run build_runner build --delete-conflicting-outputs
    description: Run build_runner codegen on root app

  codegen:pkg:
    run: melos exec -- fvm flutter pub run build_runner build --delete-conflicting-outputs
    description: Run build_runner codegen on targeted package(s)
    packageFilters:
      dependsOn:
        - build_runner

  clean:
    run: melos exec -- fvm flutter clean
    description: Run flutter clean in all packages

  outdated:
    run: melos exec -- fvm flutter pub outdated
    description: Check outdated dependencies in all packages
