// Mocks generated by Mockito 5.4.6 from annotations
// in nhasixapp/test/presentation/blocs/search/search_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:logger/logger.dart' as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:nhasixapp/data/datasources/local/local_data_source.dart' as _i6;
import 'package:nhasixapp/data/models/content_model.dart' as _i7;
import 'package:nhasixapp/data/models/download_status_model.dart' as _i9;
import 'package:nhasixapp/data/models/history_model.dart' as _i10;
import 'package:nhasixapp/data/models/tag_model.dart' as _i8;
import 'package:nhasixapp/domain/entities/entities.dart' as _i3;
import 'package:nhasixapp/domain/repositories/repositories.dart' as _i2;
import 'package:nhasixapp/domain/usecases/content/search_content_usecase.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeContentListResult_0 extends _i1.SmartFake
    implements _i2.ContentListResult {
  _FakeContentListResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserPreferences_1 extends _i1.SmartFake
    implements _i3.UserPreferences {
  _FakeUserPreferences_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SearchContentUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchContentUseCase extends _i1.Mock
    implements _i4.SearchContentUseCase {
  MockSearchContentUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.ContentListResult> call(_i3.SearchFilter? filter) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [filter],
        ),
        returnValue:
            _i5.Future<_i2.ContentListResult>.value(_FakeContentListResult_0(
          this,
          Invocation.method(
            #call,
            [filter],
          ),
        )),
      ) as _i5.Future<_i2.ContentListResult>);
}

/// A class which mocks [LocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalDataSource extends _i1.Mock implements _i6.LocalDataSource {
  MockLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> cacheContentList(List<_i7.ContentModel>? contents) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheContentList,
          [contents],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i7.ContentModel>> getCachedContentList({
    int? page = 1,
    int? limit = 20,
    String? language,
    String? category,
    List<String>? excludeIds,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedContentList,
          [],
          {
            #page: page,
            #limit: limit,
            #language: language,
            #category: category,
            #excludeIds: excludeIds,
          },
        ),
        returnValue:
            _i5.Future<List<_i7.ContentModel>>.value(<_i7.ContentModel>[]),
      ) as _i5.Future<List<_i7.ContentModel>>);

  @override
  _i5.Future<_i7.ContentModel?> getContentById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getContentById,
          [id],
        ),
        returnValue: _i5.Future<_i7.ContentModel?>.value(),
      ) as _i5.Future<_i7.ContentModel?>);

  @override
  _i5.Future<List<_i7.ContentModel>> searchCachedContent({
    String? query,
    List<String>? includeTags,
    List<String>? excludeTags,
    String? language,
    String? category,
    int? page = 1,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchCachedContent,
          [],
          {
            #query: query,
            #includeTags: includeTags,
            #excludeTags: excludeTags,
            #language: language,
            #category: category,
            #page: page,
            #limit: limit,
          },
        ),
        returnValue:
            _i5.Future<List<_i7.ContentModel>>.value(<_i7.ContentModel>[]),
      ) as _i5.Future<List<_i7.ContentModel>>);

  @override
  _i5.Future<void> deleteExpiredCache(
          {Duration? maxAge = const Duration(days: 7)}) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteExpiredCache,
          [],
          {#maxAge: maxAge},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> cacheContent(_i7.ContentModel? content) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheContent,
          [content],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i8.TagModel>> getAllTags({
    String? type,
    int? minCount,
    int? limit = 100,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllTags,
          [],
          {
            #type: type,
            #minCount: minCount,
            #limit: limit,
          },
        ),
        returnValue: _i5.Future<List<_i8.TagModel>>.value(<_i8.TagModel>[]),
      ) as _i5.Future<List<_i8.TagModel>>);

  @override
  _i5.Future<List<_i8.TagModel>> searchTags(
    String? query, {
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchTags,
          [query],
          {#limit: limit},
        ),
        returnValue: _i5.Future<List<_i8.TagModel>>.value(<_i8.TagModel>[]),
      ) as _i5.Future<List<_i8.TagModel>>);

  @override
  _i5.Future<void> addToFavorites(
    String? contentId, {
    int? categoryId = 1,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addToFavorites,
          [contentId],
          {#categoryId: categoryId},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> removeFromFavorites(
    String? contentId, {
    int? categoryId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFromFavorites,
          [contentId],
          {#categoryId: categoryId},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i7.ContentModel>> getFavorites({
    int? categoryId,
    int? page = 1,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFavorites,
          [],
          {
            #categoryId: categoryId,
            #page: page,
            #limit: limit,
          },
        ),
        returnValue:
            _i5.Future<List<_i7.ContentModel>>.value(<_i7.ContentModel>[]),
      ) as _i5.Future<List<_i7.ContentModel>>);

  @override
  _i5.Future<bool> isFavorited(
    String? contentId, {
    int? categoryId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #isFavorited,
          [contentId],
          {#categoryId: categoryId},
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<int> createFavoriteCategory(String? name) => (super.noSuchMethod(
        Invocation.method(
          #createFavoriteCategory,
          [name],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getFavoriteCategories() =>
      (super.noSuchMethod(
        Invocation.method(
          #getFavoriteCategories,
          [],
        ),
        returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<void> saveDownloadStatus(_i9.DownloadStatusModel? status) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveDownloadStatus,
          [status],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i9.DownloadStatusModel?> getDownloadStatus(String? contentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDownloadStatus,
          [contentId],
        ),
        returnValue: _i5.Future<_i9.DownloadStatusModel?>.value(),
      ) as _i5.Future<_i9.DownloadStatusModel?>);

  @override
  _i5.Future<List<_i9.DownloadStatusModel>> getAllDownloads({
    _i3.DownloadState? state,
    int? page = 1,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllDownloads,
          [],
          {
            #state: state,
            #page: page,
            #limit: limit,
          },
        ),
        returnValue: _i5.Future<List<_i9.DownloadStatusModel>>.value(
            <_i9.DownloadStatusModel>[]),
      ) as _i5.Future<List<_i9.DownloadStatusModel>>);

  @override
  _i5.Future<void> deleteDownloadStatus(String? contentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteDownloadStatus,
          [contentId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> saveHistory(_i10.HistoryModel? history) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveHistory,
          [history],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i10.HistoryModel?> getHistory(String? contentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getHistory,
          [contentId],
        ),
        returnValue: _i5.Future<_i10.HistoryModel?>.value(),
      ) as _i5.Future<_i10.HistoryModel?>);

  @override
  _i5.Future<List<_i10.HistoryModel>> getAllHistory({
    int? page = 1,
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllHistory,
          [],
          {
            #page: page,
            #limit: limit,
          },
        ),
        returnValue:
            _i5.Future<List<_i10.HistoryModel>>.value(<_i10.HistoryModel>[]),
      ) as _i5.Future<List<_i10.HistoryModel>>);

  @override
  _i5.Future<void> clearHistory() => (super.noSuchMethod(
        Invocation.method(
          #clearHistory,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteHistory(String? contentId) => (super.noSuchMethod(
        Invocation.method(
          #deleteHistory,
          [contentId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> saveUserPreferences(_i3.UserPreferences? preferences) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveUserPreferences,
          [preferences],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i3.UserPreferences> getUserPreferences() => (super.noSuchMethod(
        Invocation.method(
          #getUserPreferences,
          [],
        ),
        returnValue:
            _i5.Future<_i3.UserPreferences>.value(_FakeUserPreferences_1(
          this,
          Invocation.method(
            #getUserPreferences,
            [],
          ),
        )),
      ) as _i5.Future<_i3.UserPreferences>);

  @override
  _i5.Future<void> addSearchHistory(String? query) => (super.noSuchMethod(
        Invocation.method(
          #addSearchHistory,
          [query],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<String>> getSearchHistory({int? limit = 20}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSearchHistory,
          [],
          {#limit: limit},
        ),
        returnValue: _i5.Future<List<String>>.value(<String>[]),
      ) as _i5.Future<List<String>>);

  @override
  _i5.Future<void> clearSearchHistory() => (super.noSuchMethod(
        Invocation.method(
          #clearSearchHistory,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<Map<String, int>> getDatabaseStats() => (super.noSuchMethod(
        Invocation.method(
          #getDatabaseStats,
          [],
        ),
        returnValue: _i5.Future<Map<String, int>>.value(<String, int>{}),
      ) as _i5.Future<Map<String, int>>);

  @override
  _i5.Future<void> cleanupOldData() => (super.noSuchMethod(
        Invocation.method(
          #cleanupOldData,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [Logger].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogger extends _i1.Mock implements _i11.Logger {
  @override
  _i5.Future<void> get init => (super.noSuchMethod(
        Invocation.getter(#init),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void v(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #v,
          [message],
          {
            #time: time,
            #error: error,
            #stackTrace: stackTrace,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void t(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #t,
          [message],
          {
            #time: time,
            #error: error,
            #stackTrace: stackTrace,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void d(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #d,
          [message],
          {
            #time: time,
            #error: error,
            #stackTrace: stackTrace,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void i(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #i,
          [message],
          {
            #time: time,
            #error: error,
            #stackTrace: stackTrace,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void w(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #w,
          [message],
          {
            #time: time,
            #error: error,
            #stackTrace: stackTrace,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void e(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #e,
          [message],
          {
            #time: time,
            #error: error,
            #stackTrace: stackTrace,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void wtf(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #wtf,
          [message],
          {
            #time: time,
            #error: error,
            #stackTrace: stackTrace,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void f(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #f,
          [message],
          {
            #time: time,
            #error: error,
            #stackTrace: stackTrace,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void log(
    _i11.Level? level,
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #log,
          [
            level,
            message,
          ],
          {
            #time: time,
            #error: error,
            #stackTrace: stackTrace,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool isClosed() => (super.noSuchMethod(
        Invocation.method(
          #isClosed,
          [],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i5.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
