// Mocks generated by Mockito 5.4.6 from annotations
// in nhasixapp/test/integration/content_bloc_integration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:nhasixapp/data/datasources/local/local_data_source.dart' as _i3;
import 'package:nhasixapp/data/models/content_model.dart' as _i5;
import 'package:nhasixapp/data/models/download_status_model.dart' as _i7;
import 'package:nhasixapp/data/models/history_model.dart' as _i9;
import 'package:nhasixapp/data/models/tag_model.dart' as _i6;
import 'package:nhasixapp/domain/entities/download_status.dart' as _i8;
import 'package:nhasixapp/domain/entities/user_preferences.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserPreferences_0 extends _i1.SmartFake
    implements _i2.UserPreferences {
  _FakeUserPreferences_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalDataSource extends _i1.Mock implements _i3.LocalDataSource {
  MockLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> cacheContentList(List<_i5.ContentModel>? contents) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheContentList,
          [contents],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.ContentModel>> getCachedContentList({
    int? page = 1,
    int? limit = 20,
    String? language,
    String? category,
    List<String>? excludeIds,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedContentList,
          [],
          {
            #page: page,
            #limit: limit,
            #language: language,
            #category: category,
            #excludeIds: excludeIds,
          },
        ),
        returnValue:
            _i4.Future<List<_i5.ContentModel>>.value(<_i5.ContentModel>[]),
      ) as _i4.Future<List<_i5.ContentModel>>);

  @override
  _i4.Future<_i5.ContentModel?> getContentById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getContentById,
          [id],
        ),
        returnValue: _i4.Future<_i5.ContentModel?>.value(),
      ) as _i4.Future<_i5.ContentModel?>);

  @override
  _i4.Future<List<_i5.ContentModel>> searchCachedContent({
    String? query,
    List<String>? includeTags,
    List<String>? excludeTags,
    String? language,
    String? category,
    int? page = 1,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchCachedContent,
          [],
          {
            #query: query,
            #includeTags: includeTags,
            #excludeTags: excludeTags,
            #language: language,
            #category: category,
            #page: page,
            #limit: limit,
          },
        ),
        returnValue:
            _i4.Future<List<_i5.ContentModel>>.value(<_i5.ContentModel>[]),
      ) as _i4.Future<List<_i5.ContentModel>>);

  @override
  _i4.Future<void> deleteExpiredCache(
          {Duration? maxAge = const Duration(days: 7)}) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteExpiredCache,
          [],
          {#maxAge: maxAge},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> cacheContent(_i5.ContentModel? content) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheContent,
          [content],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i6.TagModel>> getAllTags({
    String? type,
    int? minCount,
    int? limit = 100,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllTags,
          [],
          {
            #type: type,
            #minCount: minCount,
            #limit: limit,
          },
        ),
        returnValue: _i4.Future<List<_i6.TagModel>>.value(<_i6.TagModel>[]),
      ) as _i4.Future<List<_i6.TagModel>>);

  @override
  _i4.Future<List<_i6.TagModel>> searchTags(
    String? query, {
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchTags,
          [query],
          {#limit: limit},
        ),
        returnValue: _i4.Future<List<_i6.TagModel>>.value(<_i6.TagModel>[]),
      ) as _i4.Future<List<_i6.TagModel>>);

  @override
  _i4.Future<void> addToFavorites(
    String? contentId, {
    int? categoryId = 1,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addToFavorites,
          [contentId],
          {#categoryId: categoryId},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> removeFromFavorites(
    String? contentId, {
    int? categoryId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFromFavorites,
          [contentId],
          {#categoryId: categoryId},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.ContentModel>> getFavorites({
    int? categoryId,
    int? page = 1,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFavorites,
          [],
          {
            #categoryId: categoryId,
            #page: page,
            #limit: limit,
          },
        ),
        returnValue:
            _i4.Future<List<_i5.ContentModel>>.value(<_i5.ContentModel>[]),
      ) as _i4.Future<List<_i5.ContentModel>>);

  @override
  _i4.Future<bool> isFavorited(
    String? contentId, {
    int? categoryId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #isFavorited,
          [contentId],
          {#categoryId: categoryId},
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<int> createFavoriteCategory(String? name) => (super.noSuchMethod(
        Invocation.method(
          #createFavoriteCategory,
          [name],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getFavoriteCategories() =>
      (super.noSuchMethod(
        Invocation.method(
          #getFavoriteCategories,
          [],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<void> saveDownloadStatus(_i7.DownloadStatusModel? status) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveDownloadStatus,
          [status],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i7.DownloadStatusModel?> getDownloadStatus(String? contentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDownloadStatus,
          [contentId],
        ),
        returnValue: _i4.Future<_i7.DownloadStatusModel?>.value(),
      ) as _i4.Future<_i7.DownloadStatusModel?>);

  @override
  _i4.Future<List<_i7.DownloadStatusModel>> getAllDownloads({
    _i8.DownloadState? state,
    int? page = 1,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllDownloads,
          [],
          {
            #state: state,
            #page: page,
            #limit: limit,
          },
        ),
        returnValue: _i4.Future<List<_i7.DownloadStatusModel>>.value(
            <_i7.DownloadStatusModel>[]),
      ) as _i4.Future<List<_i7.DownloadStatusModel>>);

  @override
  _i4.Future<void> deleteDownloadStatus(String? contentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteDownloadStatus,
          [contentId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> saveHistory(_i9.HistoryModel? history) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveHistory,
          [history],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i9.HistoryModel?> getHistory(String? contentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getHistory,
          [contentId],
        ),
        returnValue: _i4.Future<_i9.HistoryModel?>.value(),
      ) as _i4.Future<_i9.HistoryModel?>);

  @override
  _i4.Future<List<_i9.HistoryModel>> getAllHistory({
    int? page = 1,
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllHistory,
          [],
          {
            #page: page,
            #limit: limit,
          },
        ),
        returnValue:
            _i4.Future<List<_i9.HistoryModel>>.value(<_i9.HistoryModel>[]),
      ) as _i4.Future<List<_i9.HistoryModel>>);

  @override
  _i4.Future<void> clearHistory() => (super.noSuchMethod(
        Invocation.method(
          #clearHistory,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteHistory(String? contentId) => (super.noSuchMethod(
        Invocation.method(
          #deleteHistory,
          [contentId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> saveUserPreferences(_i2.UserPreferences? preferences) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveUserPreferences,
          [preferences],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.UserPreferences> getUserPreferences() => (super.noSuchMethod(
        Invocation.method(
          #getUserPreferences,
          [],
        ),
        returnValue:
            _i4.Future<_i2.UserPreferences>.value(_FakeUserPreferences_0(
          this,
          Invocation.method(
            #getUserPreferences,
            [],
          ),
        )),
      ) as _i4.Future<_i2.UserPreferences>);

  @override
  _i4.Future<void> addSearchHistory(String? query) => (super.noSuchMethod(
        Invocation.method(
          #addSearchHistory,
          [query],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<String>> getSearchHistory({int? limit = 20}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSearchHistory,
          [],
          {#limit: limit},
        ),
        returnValue: _i4.Future<List<String>>.value(<String>[]),
      ) as _i4.Future<List<String>>);

  @override
  _i4.Future<void> clearSearchHistory() => (super.noSuchMethod(
        Invocation.method(
          #clearSearchHistory,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, int>> getDatabaseStats() => (super.noSuchMethod(
        Invocation.method(
          #getDatabaseStats,
          [],
        ),
        returnValue: _i4.Future<Map<String, int>>.value(<String, int>{}),
      ) as _i4.Future<Map<String, int>>);

  @override
  _i4.Future<void> cleanupOldData() => (super.noSuchMethod(
        Invocation.method(
          #cleanupOldData,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
